// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DarkModeToggle from "./islands/DarkModeToggle.tsx";
import * as $GitHubPreview from "./islands/GitHubPreview.tsx";
import * as $LinkPreview from "./islands/LinkPreview.tsx";
import * as $OsuPreview from "./islands/OsuPreview.tsx";
import * as $TwitchPreview from "./islands/TwitchPreview.tsx";
import * as $TwitterPreview from "./islands/TwitterPreview.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DarkModeToggle.tsx": $DarkModeToggle,
    "./islands/GitHubPreview.tsx": $GitHubPreview,
    "./islands/LinkPreview.tsx": $LinkPreview,
    "./islands/OsuPreview.tsx": $OsuPreview,
    "./islands/TwitchPreview.tsx": $TwitchPreview,
    "./islands/TwitterPreview.tsx": $TwitterPreview,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
